[CmdletBinding()]
param([switch]$Check)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$target = Join-Path $root 'docs/CONTROLLER_BINDINGS.md'
$names = @{
    thumbstick='stick'; joystick='stick'; left_stick='stick'; right_stick='stick'
    trigger='trigger'; grip='grip'; trackpad='trackpad'; application_menu='menu'; system='system/menu'
    l1='L1'; r1='R1'; l2='L2'; r2='R2'; square='Square'; cross='Cross'
    triangle='Triangle'; circle='Circle'; options='Options'; create='Create'
    a='A'; b='B'; x='X'; y='Y'
}
function Get-Controls($graph, [string[]]$sets, [string]$action) {
    $controls = foreach ($set in $sets) {
        foreach ($row in $graph.bindings.$set.sources) {
            foreach ($event in $row.inputs.PSObject.Properties) {
                if ($event.Value.output -notmatch "/in/$action`$") { continue }
                $parts = $row.path.Split('/')
                $hand = if ($parts[3] -eq 'left') { 'Left' } else { 'Right' }
                $component = $parts[-1]
                $name = if ($names.ContainsKey($component)) { $names[$component] } else { $component }
                $behavior = switch ($event.Name) {
                    'position' { 'deflection' }
                    'click' {
                        if ($row.PSObject.Properties.Name -contains 'parameters' -and
                            $row.parameters.PSObject.Properties.Name -contains 'force_input' -and
                            $row.parameters.force_input -eq 'force') { 'squeeze' } else { 'press' }
                    }
                    default { $event.Name }
                }
                "$hand $name $behavior"
            }
        }
    }
    $controls = @($controls | Sort-Object -Unique)
    if ($controls.Count -eq 0) { return 'Not assigned' }
    return $controls -join ' / '
}
$lines = @(
    '# Default controller bindings', '',
    '<!-- Generated by tools/Write-ControllerControlsReference.ps1 from the distributed binding graphs. -->', '',
    'These are the current source defaults shared by the three games. SteamVR can retain a different saved custom layout. Black Plague can open the active layout from **Options > VR Settings > Controller bindings (SteamVR)**. Overture and Requiem use the SteamVR dashboard binding editor. Overture''s v1.0.3 in-game shortcut was removed in v1.0.4 after an external pre-menu crash report.', '',
    'Stick deflection supplies a Vector2 Position action; stick press supplies a separate boolean Click. Turning does not toggle crouch unless the stick is pressed. Button crouch is a toggle in Button/Hybrid mode; Physical mode uses headset height.', '',
    'Index grip and trackpad presses use force with explicit 0.65 activation / 0.60 release thresholds, following Valve Moondust. Touch/Pico recenter is deliberately unassigned to avoid stealing a gameplay button or naming a nonexistent button; use the calibration menu where available or assign a custom SteamVR binding.', '',
    'The offhand trigger is activated for interaction by Overture. Black Plague/Requiem currently activate the dominant gameplay set only. Vive/WMR retain compatibility layouts: the Overture offhand trigger can also activate Jump; Vive menu clicks also recenter. Those legacy exceptions are listed here rather than treated as full controller parity. Device validation remains in the [controller ledger](TRILOGY_PARITY_PLAN.md#controller-profiles-and-distribution).', ''
)
$actions = [ordered]@{ move='Move'; sprint='Sprint'; turn='Turn'; crouch='Toggle crouch'; interact='Interact/use tool'; quick_light='Quick light'; inventory='Inventory'; notebook='Notebook'; holster='Holster'; examine='Examine'; jump='Jump'; pause='Pause'; recenter='Recenter' }
$ui = [ordered]@{ select='Select'; drag='Drag/alternate'; back='Back/context'; close='Close'; recenter='Recenter' }
foreach ($file in Get-ChildItem -LiteralPath (Join-Path $root 'assets/openvr/bindings') -Filter '*.json' | Sort-Object Name) {
    $graph = Get-Content -LiteralPath $file.FullName -Raw | ConvertFrom-Json
    $lines += @("## $($graph.name.Replace('Penumbra VR - ',''))", '', "SteamVR type: ``$($graph.controller_type)``. Default file: ``$($file.Name)``.", '', '| Gameplay action | Right-handed | Left-handed |', '| --- | --- | --- |')
    foreach ($action in $actions.Keys) {
        $right = Get-Controls $graph @('/actions/global','/actions/gameplay') $action
        $left = Get-Controls $graph @('/actions/global','/actions/gameplay_left') $action
        $lines += "| $($actions[$action]) | $right | $left |"
    }
    $lines += @('', '| UI action | Right-handed | Left-handed |', '| --- | --- | --- |')
    foreach ($action in $ui.Keys) {
        $right = Get-Controls $graph @('/actions/global','/actions/ui') $action
        $left = Get-Controls $graph @('/actions/global','/actions/ui_left') $action
        $lines += "| $($ui[$action]) | $right | $left |"
    }
    $lines += ''
}
$text = ($lines -join "`n") + "`n"
if ($Check) {
    if (-not (Test-Path -LiteralPath $target) -or [IO.File]::ReadAllText($target).Replace("`r`n","`n") -cne $text) {
        throw 'Controller reference differs from the actual graphs. Run tools/Write-ControllerControlsReference.ps1.'
    }
} else { [IO.File]::WriteAllText($target, $text, [Text.UTF8Encoding]::new($false)) }
